### ISSUE TITLE
Error with eventGrid binding type

### ISSUE THREAD

**Issue by chazguerrero** [Azure/azure-functions-extension-bundles#10]
Error:

Function (********) Error: The binding type(s) 'eventGrid' are not registered. Please ensure the type is correct and the binding extension is installed.
Session Id: 469891e8da0943c1a5e26080eb945c51

Timestamp: 2020-02-21T17:49:33.728Z

Based on the documentation https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-event-grid-output?tabs=javascript and the code in https://github.com/Azure/azure-functions-eventgrid-extension/blob/dev/src/EventGridExtension/OutputBinding/EventGridAttribute.cs

I think https://github.com/Azure/azure-functions-extension-bundles/blob/master/src/Microsoft.Azure.Functions.ExtensionBundle/extensions.json#L54 needs to be changed to 

```json
    {
        "id": "Microsoft.Azure.WebJobs.Extensions.EventGrid",
        "version": "2.1.0",
        "name": "EventGrid",
        "bindings": [
            "eventgridtrigger",
            "eventgrid"
        ]
    },
```

Thanks

**Comment by soninaren** [comment]
Addressed in the commits below.
https://github.com/Azure/azure-functions-extension-bundles/commit/8753d86fdb4170736df6e3d28857cdcb13022d5d
https://github.com/Azure/azure-functions-extension-bundles/commit/509fa9d940dfc3c1366d2723a366de549d62f684

**Comment by acomley** [comment]
I get the following error locally and when deployed:
`The 'XXXXXX' function is in error: The binding type(s) 'eventGrid' are not registered. Please ensure the type is correct and the binding extension is installed.`

If this isn't the correct place for this, then let me know the correct spot.
