### ISSUE TITLE
Add Cosmos v4 to preview bundle

### ISSUE THREAD

**Issue by cachai2** [Azure/azure-functions-extension-bundles#104]
Nuget: https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.CosmosDB/4.0.0-preview2

Cosmos is previewing the v4 extension 9/15. We should have their extension available in the preview bundle ASAP.

**Comment by cachai2** [comment]
We can create a new id bundle similar to what we did for the preview v3 bundle. 

It might get confusing if we have it in the v3 preview bundle as when we GA v3 bundle, we would need to snap back Cosmos to the current version. v4 preview bundle would be confusing if v3 is still not GA.

**Comment by fabiocav** [comment]
V3 is GA and this would need to go into the V4 preview bundle (which needs to be created).

**Comment by fabiocav** [comment]
Work has been completed. @madelinegordon is going through additional validation.

**Comment by fabiocav** [comment]
Closing as completed.
