### ISSUE TITLE
Please add Azure Web PubSub to the functions extension bundle.

### ISSUE THREAD

**Issue by mithunshanbhag** [Azure/azure-functions-extension-bundles#107]
[Azure Web PubSub](https://docs.microsoft.com/en-in/azure/azure-web-pubsub/) (currently in preview) has [Azure function triggers, input/output bindings](https://docs.microsoft.com/en-in/azure/azure-web-pubsub/reference-functions-bindings?tabs=javascript).

Currently, [Microsoft.Azure.WebJobs.Extensions.WebPubSub](https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.WebPubSub/1.0.0-beta.3) is not a part of the functions extension bundle and I'm forced to register it separately. 

```
func extensions install --package Microsoft.Azure.WebJobs.Extensions.WebPubSub --version 1.0.0-beta.3
```

Would it be possible to add this package to the extension bundle?

**Edit**: Submitted PR #108 to address this issue. Can someone please take a look?

**Comment by fabiocav** [comment]
PR merged.
