### ISSUE TITLE
update to newer Microsoft.Azure.WebJobs.Extensions.Storage?

### ISSUE THREAD

**Issue by chanes-cds** [Azure/azure-functions-extension-bundles#11]
There are issues with blog triggers against ADLSv2 storage documented here https://github.com/Azure/azure-webjobs-sdk/issues/2395 and fixed here https://github.com/Azure/azure-webjobs-sdk/commit/77f8cd0e62178463135df39f7d800791cc4a504f#diff-2f5bfbd695c25c7ade10fc0bb5b83eec.  Are their plans to update soon from 3.0.10 to say 3.0.17?

**Comment by lankaapura** [comment]
when can we expect a version with Microsoft.Azure.WebJobs.Extensions.Storage 3.0.11. We can't use python azure functions with data lake due to the following issue. Or is it possible to get a preview package at least?
https://github.com/microsoft/vscode-azurefunctions/issues/1725

**Comment by soninaren** [comment]
@lankaapura We are going to try and release an updated version of extension bundle in a couple of weeks.

**Comment by lankaapura** [comment]
Thanks @soninaren. can we at leaset get a preview version?

**Comment by profblackjack** [comment]
Very much interested in this fix being released! It's really impeding my project using a v2 blob storage as an input binding.
