### ISSUE TITLE
Upgrade Microsoft.Azure.WebJobs.Extensions.EventGrid to 3.0.1 in bundle

### ISSUE THREAD

**Issue by smafre** [Azure/azure-functions-extension-bundles#130]
I recently reported an issue with Microsoft.Azure.WebJobs.Extensions.EventGrid version 3.0.0. This was fixed and a new version has been released (3.0.1: https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.EventGrid/3.0.1).

I though that using extension bundle version 3.x (`"version": "[3.3.0, 4.0.0)"`) automatically caused us to use the latest major version of each extension, so we would get the latests version of the EventGrid extension without doing anything. This does not seem to be the case. I deleted my local cached version of extension bundle version 3.x so it would be downloaded again, but I still get version 3.0.0 of Microsoft.Azure.WebJobs.Extensions.EventGrid.

Do you have to trigger a new release or a pipeline run so we can get version 3.0.1 of the EventGrid extension and get our issue resolved?

Original issue: https://github.com/Azure/azure-sdk-for-net/issues/25810

**Comment by smafre** [comment]
/cc @soninaren

Anyone reading these issues? It's kind of urgent for us to get this issue of ours fixed.

**Comment by soninaren** [comment]
@smafre latest version of Microsoft.Azure.WebJobs.Extensions.EventGrid was release just 7 days ago. This is too short of a time to cut a release of a new extension bundle, validate and safely deploy it across Azure.  

A new release of extension bundle v3.5.0 has been initiated already. It is currently in validation phase. It does include Microsoft.Azure.WebJobs.Extensions.EventGrid version 3.0.1. However the release is unlikely to finish before end of the year.

**Comment by smafre** [comment]
Ok, good to know. Thanks for the response.
