### ISSUE TITLE
Extension Bundles v2.8.5 and v3.5.0 have been abandoned

### ISSUE THREAD

**Issue by VpOfEngineering** [Azure/azure-functions-extension-bundles#141]
We have abandoned two versions of Extension Bundles: `2.8.5` and `3.5.0`. The next versions released will be `2.9.0` and `3.6.0`.

Please keep any questions and discussions under this issue. Thank you.

**Comment by kwill-MSFT** [comment]
Any timeframe on these releases?  I am waiting on the durable task storage fixes in https://github.com/Azure/durabletask/releases/tag/durabletask.azurestorage-v1.9.3.

**Comment by soninaren** [comment]
Closing this one as an updated version of bundle v2 and v3 have been released.
