### ISSUE TITLE
What does the "majorVersion" refer to?

### ISSUE THREAD

**Issue by ericthomas1** [Azure/azure-functions-extension-bundles#230]
Hello,

What does the "majorVersion" value in the extension bundle refer to?

Does this value indicate any change to the binding itself?

**Example**:
- If I have an Azure Function that uses a single input binding of "queue", is there any change to the performance of the queue binding whether I'm using extension bundle version `[2.*, 3.0.0)` or `[3.*, 4.0.0)`?

**Comment by manvkaur** [comment]
@ericthomas1 - 

- Extension release 2.x has major version 4 of Storage package, which means 4.x Nuget package for Microsoft.Azure.WebJobs.Extensions.Storage got downloaded - https://github.com/Azure/azure-functions-extension-bundles/blob/ee664bf4f0572bab10d2686730d3b3ff697249cf/src/Microsoft.Azure.Functions.ExtensionBundle/extensions.json#L4

- Extension release 3.x and release 4.x has major version 5 of storage packages, which means latest 5.x (GA version) will be pulled for [Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues](https://www.nuget.org/packages/Microsoft.Azure.Functions.Worker.Extensions.Storage.Queues/#versions-body-tab) at the time of extension bundle download.
https://github.com/Azure/azure-functions-extension-bundles/blob/55829628c31333630e2a82fb3399022107021eba/src/Microsoft.Azure.Functions.ExtensionBundle/extensions.json#L23
https://github.com/Azure/azure-functions-extension-bundles/blob/16124263a8a6a6d9f73819a8da5da3fefb71e283/src/Microsoft.Azure.Functions.ExtensionBundle/extensions.json#L15

For details, you can refer the document specific to [Azure Queue storage trigger and bindings for Azure Functions overview](https://learn.microsoft.com/en-us/azure/azure-functions/functions-bindings-storage-queue?tabs=isolated-process%2Cextensionv5%2Cextensionv3&pivots=programming-language-csharp#storage-extension-5x-and-higher) which details difference between 5.x and previous versions of storage packages and changes that have been introduced.

**Comment by manvkaur** [comment]
@BigMorty , @vrdmr , Another example of how documentation confuses the users between extension versions and bundles version.

Another such example - #391
