### ISSUE TITLE
List extension versions in each release

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-extension-bundles#25]
I think it would be useful to include what versions of the extensions are in each bundles release. Maybe we can just include a link to the tagged version of the extension.json file in the release notes.

As we ship v2, we'll want to have one place where we can see what are the latest v1 and v2 bundle versions, as well as the extensions that are in them. I'd like to update this [page in docs](https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-register) with information about how to switch between bundle versions and then link to the latest versions. Not sure where this information could live. Could be in docs, or a readme or wiki in this repo.

@soninaren @sidkri What do you think?

**Comment by soninaren** [comment]
Yes, having this information available in release notes would be be helpful for sure. Not that we are going to have a much more frequent bundle release, a dedicated reference documentation page for bundle content would be helpful. We can use release notes for that purpose. Also open to other suggestions for hosting this information in an automated manner.

**Comment by soninaren** [comment]
This is complete
