### ISSUE TITLE
Update bundle builds to check and flag vulnerabilities in the resolved dependencies. 

### ISSUE THREAD

**Issue by soninaren** [Azure/azure-functions-extension-bundles#265]

**Comment by mapalan** [comment]
Bundle builds are failing for #266. 
From the build pipeline, it seems like the `SBOMUtilSASUrl` environment variable not set correctly, causing the build to fail on the `DownloadManifestUtility` step

**Comment by fabiocav** [comment]
Duplicate of #309

**Comment by soninaren** [comment]
@fabiocav My suggestion that this was a duplicate issue was actually incorrect. Both work items address different issues.
