### ISSUE TITLE
[CustomHandler]Generate  bundles with latest templates

### ISSUE THREAD

**Issue by pragnagopa** [Azure/azure-functions-extension-bundles#27]
cc @soninaren
https://github.com/Azure/azure-functions-templates/issues/965

**Comment by pragnagopa** [comment]
Testing completed using private bits. Will proceed with release activities next sprint.

**Comment by fabiocav** [comment]
This is blocked by pipeline updates currently in progress.

**Comment by fabiocav** [comment]
Pipeline has been updated. Release has been updated.
