### ISSUE TITLE
Create a test to validate that bundles updates do not move dependencies outside of safe ranges

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-extension-bundles#309]
This should mimic the behavior we have with the host dependency validation tests.

**Comment by surgupta-msft** [comment]
- [x] Changes in v4.x branch - https://github.com/Azure/azure-functions-extension-bundles/pull/310
- [ ] Changes in v4.x-preview branch -
- [ ] Changes in v3.x branch - https://github.com/Azure/azure-functions-extension-bundles/pull/317

**Comment by surgupta-msft** [comment]
- Changes in v4.x branch
     - [x] https://github.com/Azure/azure-functions-extension-bundles/pull/310
     - [ ] https://github.com/Azure/azure-functions-extension-bundles/pull/324
- Changes in v4.x-preview branch 
     - [x] https://github.com/Azure/azure-functions-extension-bundles/pull/318
- Changes in v3.x branch
     - [x] https://github.com/Azure/azure-functions-extension-bundles/pull/317
