### ISSUE TITLE
Azure.Identity 1.7 is deprecated, need to use Azure.Identity 1.10 instead

### ISSUE THREAD

**Issue by rickygzz** [Azure/azure-functions-extension-bundles#312]
[Extensions Bundles release 4.8.0](https://github.com/Azure/azure-functions-extension-bundles/releases/tag/4.8.0)  uses Azure.Identity.dll v1.7 which is deprecated.

Is there any plan to use v1.10+ instead in the next release?

Our scans detects vulnerabilities using v1.7 . Azure.Identity.dll version 1.7 is deprecated and vulnerable, please update to version 1.10+

![Azure Identity1 70](https://github.com/Azure/azure-functions-extension-bundles/assets/36200981/7549ff58-ac0b-45d1-a1fd-d93171d463df)

https://www.nuget.org/packages/Azure.Identity#versions-body-tab

![image](https://github.com/Azure/azure-functions-extension-bundles/assets/36200981/221d4487-121c-41ea-8ea8-70fcca4c61a5)

**Comment by rickygzz** [comment]
Thank you for fixing it @soninaren ! You rock!

**Comment by SharPiy** [comment]
Thank you for making this fix. I think the PR is yet to be merged. Can we merge and publish it?

**Comment by billangli** [comment]
Hi folks, is there a plan to bump the version of Azure.Identity in ExtensionBundles v2 as well? 

v2.30.0 still has the Azure.Identity 1.5.0 package. This was found in the Azure Functions Dotnet image (/FuncExtensionBundles/Microsoft.Azure.Functions.ExtensionBundle/2.30.0/bin_v3/linux-x64/function.deps.json)
![image](https://github.com/Azure/azure-functions-extension-bundles/assets/15698580/c046c10b-daea-4375-a605-0bad60f72eac)


I built the latest from the v.2.x branch locally and it's using 1.5.0
![image](https://github.com/Azure/azure-functions-extension-bundles/assets/15698580/3bfc30c3-ab95-4994-84b4-05eca3583fe1)

**Comment by fabiocav** [comment]
Closing this as resolved.
