### ISSUE TITLE
SignalR bindings in bundles 1.3.3 appear to be failing in Static Web Apps functions

### ISSUE THREAD

**Issue by anthonychu** [Azure/azure-functions-extension-bundles#38]
Fix is to pin it to 1.3.2 like this: https://github.com/anthonychu/serverless-streamr/commit/4fe4cc78664314af857d2574c2b1d050ebe2ec7d

Probably needs to be bumped to the newest version of the extension (1.2.2). Should be fixed by this: https://github.com/Azure/azure-functions-signalrservice-extension/pull/132

/cc @zackliu

**Comment by bradygaster** [comment]
don't have access to link 1

**Comment by anthonychu** [comment]
Sorry, link is public now.

**Comment by zackliu** [comment]
The latest signalr binding (v1.2.2) should have fixed the issue. But still waiting for updating the bundles to make it available to all users.
Waiting for #33 #32 to be merged. @anthonychu Do you have any concern on these two PRs?

**Comment by anthonychu** [comment]
They look good to me. I don't have access to merge. @soninaren can you please take a look?

**Comment by manvkaur** [comment]
Closing this issue as the suggested PRs look to be merge already and no further comments added for more than 4 years
