### ISSUE TITLE
Extension bundles v1.3.3 seems to contain DurableTask v1.8.5 instead of v1.8.6

### ISSUE THREAD

**Issue by YusukeTobo** [Azure/azure-functions-extension-bundles#40]
Regarding about the following release note, I expect Extension bundles v1.3.3 to have DurableTask v1.8.6.
  
  https://github.com/Azure/azure-functions-extension-bundles/releases/tag/1.3.3

But, when I open its extensions.csproj from the zip file, we can see the definition below.

    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.DurableTask" Version="1.8.5" />

Extension Bundle v1.3.3 contains older version Durable Task?

As you may see the following screenshot, Object Explore of Visual Studio 2019 shows Microsoft.Azure.WebJobs.Extensions.DurableTask.dll is v1.8.5. 

![image](https://user-images.githubusercontent.com/46416479/95842350-69172980-0d81-11eb-9b80-8a24f4fa9f2b.png)

**Comment by cgillum** [comment]
@soninaren or @yojagad can either of you comment on this? According to [this commit](https://github.com/Azure/azure-functions-extension-bundles/commit/73330d88840cc846a8cfcf855f32eccc675e6818) the version of the extension should be v1.8.6, but the zip file contains v1.8.5 assemblies.

Both the Durable extension and the SignalR Service extension seem to be the wrong version.

FYI @ConnorMcMahon
