### ISSUE TITLE
Create bundles release pipeline

### ISSUE THREAD

**Issue by fabiocav** [Azure/azure-functions-extension-bundles#85]
We need a pipeline that will automatically create bundles with the latest applicable major versions of extensions. 

@soninaren to add details.

- #89
- #90
- #91
- #92
- https://github.com/Azure/azure-functions-templates/issues/1087
- https://github.com/Azure/azure-functions-templates/issues/1088
- https://github.com/Azure/azure-functions-extension-bundles/issues/93

**Comment by fabiocav** [comment]
@soninaren is working on breaking this issue down into more granular issues tracking the work to be done. Moving this to the `epics` milestone.

**Comment by soninaren** [comment]
This is now complete
